HIVE_TO_DATABRICKS_MAP = {
    "int": "INT",
    "tinyint": "TINYINT",
    "smallint": "SMALLINT",
    "bigint": "BIGINT",
    "float": "FLOAT",
    "double": "DOUBLE",
    "boolean": "BOOLEAN",
    "string": "STRING",
    "timestamp": "TIMESTAMP",
    "date": "DATE",
    "binary": "BINARY",
    "varchar": "STRING",
    "char": "STRING",
}
